<H1>DDDDD</H1><?php echo $_SESSION['id_paciente_do_familiar'];



// O AUTH.PHP VERIFICA SE A SESSION['LOGADO']== TRUE, ENTÃO É SO NÃO
//DAR O O LOGADO PARA O FAMILIAR, MAS SIM OUTRA SESSION QUE VAI VERIFICAR SE EL É FAMILIAR
//SOMENTE NA PAG DE FAMILIAR E CLARO SE ELE TIVER O LOGADO SIGNIFICA QUE ELE É USER
// LOGO  DEVE SER MOVIDO PARA A PÁGINA DE USUÁRIO;